### ISSUE TITLE
opgops-938 - nginx installations fail

### ISSUE THREAD

**Issue by dreay-moj** [ministryofjustice/nginx-formula#31]
The nginx-full=1.4.6-1ubuntu3.2 version is no longer available, and any use of this with Ubuntu 14.04 now fails.

**Comment by ashb** [comment]
We're thinking that should replace this with 'pkg.latest' of a specific version, but with refresh=False – this would mean salt would install whatever apt thinks is the latest version of the package available but would not trigger an `apt-get update` call on every highstate.

**Comment by lukaszraczylo** [comment]
```
version: '' 
```
( empty version for nginx formula in current setup ) install latest available nginx version.
https://github.com/ministryofjustice/nginx-formula/blob/e8b1050e96e7fc344b133b306f55364e3ad02143/nginx/map.jinja#L5
