### ISSUE TITLE
Add http_authorization to logstash_json log format

### ISSUE THREAD

**Issue by aldavidson** [ministryofjustice/nginx-formula#43]
PostcodeInfo uses this so that it can record usage per-api-key, but it has to do it by defining a custom json format. 

It's probably a useful thing to have in by default, even if it will be blank in most cases

**Comment by ltsampros** [comment]
The relevant PRs that fix this span across repo boundaries.

https://github.com/ministryofjustice/nginx-formula/pull/42
https://github.com/ministryofjustice/moj-docker-deploy-formula/pull/27
https://github.com/ministryofjustice/postcodeinfo-deploy/pull/44

It has been pushed to staging and the alarms stopped.

Closing.

**Comment by aldavidson** [comment]
Those commits fixed the issue of the incorrect formatting in the custom log format, but @KrisSaxton asked me to raise this as a more general feature request - if we added the authorization into the default logstash_json format defined here, then we wouldn't need custom formats at all. 

I'm going to reopen this ticket

**Comment by ltsampros** [comment]
Understood.
